package com.mdm.DynamicTable.service;

import static java.util.Objects.nonNull;
import static org.springframework.http.HttpStatus.OK;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.mdm.DynamicTable.dto.DataModelResponse;
import com.mdm.DynamicTable.dto.TableDataType;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.springframework.stereotype.Service;

@Service
@Slf4j
@RequiredArgsConstructor
public class DataModelsOrchestrationService {

  public static final String SPACE_STR = " ";
  private final DataModelService dataModelService;
  private final ObjectMapper mapper;

  public DataModelResponse createDataModel(JsonNode requestJson) throws Exception {
    //step1 create table with the required fields from json node
    String createTableSqlString = createTableFromRequestNode(
        mapper.writeValueAsString(requestJson));

    dataModelService.createTable(createTableSqlString);

    //step2 create Json schema on a fly for the object for next crud rest operations OR
    // keep these validations in another table to do these when acutal rest calls happened.

    // return DataModelResponse
    return DataModelResponse.builder().httpStatus(OK).build();
  }

  private String createTableFromRequestNode(String requestJson) throws Exception {
    StringBuilder newTableSqlBuilder = new StringBuilder("CREATE TABLE ");
    JSONObject jsonObject = (JSONObject) readJsonSimpleDemo(requestJson);
    String tableName = (String) jsonObject.get("tableName");
    JSONArray fieldsArray = (JSONArray) jsonObject.get("fields");
    Object reference = jsonObject.get("reference");

    newTableSqlBuilder.append(tableName);
    newTableSqlBuilder.append("(");
    //Auto generated id filed will be added by default to each table
    autoGenerateIdField(newTableSqlBuilder);
    //Provided table fields will be added to sql script
    generateFieldsSql(fieldsArray, newTableSqlBuilder);
    generateForeignKeys(reference, newTableSqlBuilder);
    newTableSqlBuilder.append(")");
    log.info("Generated Sql:");
    log.info(newTableSqlBuilder.toString());

    return newTableSqlBuilder.toString();
  }

  private void generateForeignKeys(Object reference, StringBuilder newTableSqlBuilder) {
    if (nonNull(reference)) {
      newTableSqlBuilder.append(",");
      JSONObject referenceNode = (JSONObject) reference;
      String tableName = (String) referenceNode.get("table");
      newTableSqlBuilder.append(SPACE_STR);
      newTableSqlBuilder.append("CONSTRAINT FK_" + tableName + " FOREIGN KEY (");
      newTableSqlBuilder.append(referenceNode.get("byField"));
      newTableSqlBuilder.append((") REFERENCES "));
      newTableSqlBuilder.append(tableName);
      newTableSqlBuilder.append("(");
      newTableSqlBuilder.append(referenceNode.get("field"));
      newTableSqlBuilder.append(")");
    }
  }

  private void autoGenerateIdField(StringBuilder newTableSqlBuilder) {
    newTableSqlBuilder.append("id");
    newTableSqlBuilder.append(SPACE_STR);
    newTableSqlBuilder.append(TableDataType.NUMBER.getName());
    newTableSqlBuilder.append(SPACE_STR);
    newTableSqlBuilder.append("GENERATED BY DEFAULT AS IDENTITY");
  }

  private void generateFieldsSql(JSONArray fieldsArray, StringBuilder newTableSqlBuilder) {
    for (Object node : fieldsArray) {
      newTableSqlBuilder.append(",");

      JSONObject fieldNode = (JSONObject) node;
      newTableSqlBuilder.append(fieldNode.get("name"));
      newTableSqlBuilder.append(SPACE_STR);

      String dataType = (String) fieldNode.get("datatype");
      TableDataType tableDataType = TableDataType.getDataType(dataType);
      newTableSqlBuilder.append(tableDataType.getDataType());
      boolean primaryKey = (Boolean) fieldNode.get("index");
      JSONObject validations = (JSONObject) fieldNode.get("validations");
      boolean isMandatory = (Boolean) validations.get("mandatory");

      switch (tableDataType) {
        case NUMBER:
          extractNumberValidations(newTableSqlBuilder, fieldNode);
          break;

        case STRING:
          extractStringValidations(newTableSqlBuilder, fieldNode);
          break;

        default:
          throw new IllegalArgumentException("No Match found for table datatype::" + tableDataType);
      }

      //Adding primarykey and nonnull constrains to fields
      if (primaryKey) {
        newTableSqlBuilder.append(SPACE_STR);
        newTableSqlBuilder.append("PRIMARY KEY");
      } else if (isMandatory) {
        newTableSqlBuilder.append(SPACE_STR);
        newTableSqlBuilder.append("NOT NULL");
      }
    }
  }

  private void extractStringValidations(StringBuilder newTableSqlBuilder, JSONObject fieldNode) {
    Object validationsObj = fieldNode.get("validations");
    newTableSqlBuilder.append("(");
    Object lengthObj = 20;

    if (nonNull(validationsObj)) {
      JSONObject validations = (JSONObject) validationsObj;
      // retrieving Number length
      lengthObj = validations.get("length");
    }

    newTableSqlBuilder.append(lengthObj);
    newTableSqlBuilder.append(")");
  }

  private void extractNumberValidations(StringBuilder newTableSqlBuilder, JSONObject fieldNode) {
    JSONObject validations = (JSONObject) fieldNode.get("validations");

    // retrieving Number length
    Object lengthObj = validations.get("length");
    newTableSqlBuilder.append("(");
    if (nonNull(lengthObj)) {
      newTableSqlBuilder.append(lengthObj);

      // retrieving Number precision
      Object precisionObj = validations.get("precision");
      if (nonNull(precisionObj)) {
        newTableSqlBuilder.append(",");
        newTableSqlBuilder.append(precisionObj);
      }
    } else {
      newTableSqlBuilder.append(20);
    }
    newTableSqlBuilder.append(")");
  }


  private Object readJsonSimpleDemo(String jsonBody) throws Exception {
    JSONParser jsonParser = new JSONParser();
    return jsonParser.parse(jsonBody);
  }
}
