spring:
  application:
    name: MASTER-DATA-MANAGEMENT-RDBMS-API-V1

data:
  endpoint: "/master/data/management/v1"

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: ["env","beans"]
server:
  port: 2101

---
spring:
  profiles: cloud
  datasource:
    url: ${vcap.services.user-provided-postgresql.credentials.url}
    username: ${vcap.services.user-provided-postgresql.credentials.username}
    password: ${vcap.services.user-provided-postgresql.credentials.password}